export interface LinkedWearablesConfiguration {
    choices: Array<string>,
    governance: string,
    image_previews: Array<string>,
    items: number,
    links: Array<string>,
    managers: Array<string>,
    marketplace_link: string,
    method: string,
    motivation: string,
    name: string,
    nft_collections: Array<string>,
    programmatically_generated: boolean,
    smart_contract: boolean,
}